# -*- coding: utf-8 -*-
"""assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18OgFgpKYY9uDsEIyxzSryFuLjOUqCIud
"""

print("Hello World!")