# -*- coding: utf-8 -*-
"""assignment_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rsrh9VPISM_mc1Q_t0dzqxJjjjUfAtp2
"""

def fibonacci(n):
    fib_sequence = [0, 1]

    while len(fib_sequence) < n:
        fib_sequence.append(fib_sequence[-1] + fib_sequence[-2])

    return fib_sequence

n = 10
print(f"Fibonacci sequence up to term {n}: {fibonacci(n)}")