# -*- coding: utf-8 -*-
"""assignment_2'.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dy9yNaOWwhvJos1s7E_9rPM0-Am0MVkE
"""

def print_positive_numbers(input_list):
    result = [num for num in input_list if num > 0]
    print(f"Input: {input_list} Output: {result}")

list1 = [12, -7, 5, 64, -14]
print_positive_numbers(list1)

list2 = [12, 14, -95, 3]
print_positive_numbers(list2)